# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
PROMPT="${pwd}$ "

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="alanpeabody"
POWERLINE_HIDE_USER_NAME="true"
POWERLINE_HIDE_HOST_NAME="true"
POWERLINE_HIDE_GIT_PROMPT_STATUS="true"
POWERLINE_SHOW_GIT_ON_RIGHT="false"

DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(rails git ruby heroku)

# User configuration

export MANPATH=/opt/local/share/man:/usr/local/man:$MANPATH

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

#export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)

# Custom Settings #

WIDTH=$(tput cols)

# easy extraction of various file types
extract () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xvjf $1    ;;
      *.tar.gz)    tar xvzf $1    ;;
      *.bz2)       bunzip2 $1     ;;
      *.rar)       unrar x $1       ;;
      *.gz)        gunzip $1      ;;
      *.tar)       tar xvf $1     ;;
      *.tbz2)      tar xvjf $1    ;;
      *.tgz)       tar xvzf $1    ;;
      *.zip)       unzip $1       ;;
      *.Z)         uncompress $1  ;;
      *.7z)        7z x $1        ;;
      *)           echo "don't know how to extract '$1'..." ;;
    esac
  else
    echo "'$1' is not valid for extraction"
  fi
}

# Creates an archive from given directory
mktar() { tar cvf  "${1%%/}.tar"     "${1%%/}/"; }
mktgz() { tar cvzf "${1%%/}.tar.gz"  "${1%%/}/"; }
mktbz() { tar cvjf "${1%%/}.tar.bz2" "${1%%/}/"; }

export EDITOR=vim

alias ff='sudo find / -name $1'

alias ccat='pygmentize -g'
alias def='sdcv $1'

alias serve='python -m SimpleHTTPServer'

# set up vim
bindkey -v

# goodies for vim mode
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

# git prompt stuff is copied from alean pebody theme local var
# allows configures [NORMAL] right indent
function zle-line-init zle-keymap-select {
    # command line vim mode
    VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
    DATE=$( date +"%H:%M" )
    # git right side notations
    RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}$(git_prompt_status)%{$reset_color%}$(git_prompt_info)%{$reset_color%} ${DATE} $EPS1"
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select
# default .4 seconds ... but why
export KEYTIMEOUT=0

## function for piping text into and getting ip address
ip_adr() {
  cat | egrep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*";
}

format_json () {
  echo "$1" | python -m json.tool;
}

ggr () {
  git grep -in --break --heading "$1" | pygmentize -l ruby | less
}

ggp () {
  git grep -in --break --heading "$1" | pygmentize -l javascript | less
}

export LESS='-R'
export LESSOPEN='|~/.lessfilter %s'

alias define='sdcv'

# im a bad speller
alias gmcsg='gcmsg'

function num_perm() {
  ls -l $1 | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf("%0o ",k);print}'
}

alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'

alias v=vim
